version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.1
        environment:
          OCHRONA_API_KEY: $OCHRONA_API_KEY
    steps:
      - checkout
      - run:
          command: |
            pip install -r ~/project/requirements.txt
      - run:
          command: |
            pip install ochrona black
      - run:
          command: |
            black --check src
      - run:
          command: |
            ochrona --file ~/project/requirements.txt --project_name ochrona-demo --alert_config {"alerting_addresses": "andrew@ochrona.dev", "alerting_rules": "not:boto3"} --report_type XML --output ~/test-results/ochrona
          when: always
      - store_test_results:
          path: ~/test-results/ochrona/

workflows:
  main:
    jobs:
      - build-and-test
