version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.1
        environment:
          OCHRONA_API_KEY: $OCHRONA_API_KEY
    steps:
      - checkout
      - run:
          command: |
            pip install -r ~/project/requirements.txt
      - run:
          command: |
            pip install ochrona black
      - run:
          command: |
            black --check src
      - run:
          command: |
            mkdir ~/project/test-results/
      - run:
          command: |
            ochrona --file ~/project/requirements.txt --project_name ochrona-demo --report_type XML --output ~/project/test-results/
          when: always
      - store_test_results:
          path: ~/project/test-results/

workflows:
  main:
    jobs:
      - build-and-test
